<a href="https://colab.research.google.com/github/Kaua281/nasa-exoplanet-analysis/blob/main/notebooks/nasa_exoplanet_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The NASA Exoplanet Archive is a database that contains information on all known exoplanets (planets outside our solar system) discovered by NASA's various space missions, ground-based observatories, and other sources. The dataset includes information such as the planet's name, mass, radius, distance from its host star, orbital period, and other physical characteristics. The dataset also includes information on the host star, such as its name, mass, and radius. The archive is updated regularly as new exoplanets are discovered, and it is a valuable resource for astronomers studying the properties and distribution of exoplanets in our galaxy.

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df = pd.read_csv("../data/cleaned_5250.csv")

In [20]:
dictionary = {
    'Column': [
        'Name',
        'Distance',
        'Stellar_magnitude',
        'Planet_type',
        'Discovery_year',
        'Mass_multiplier',
        'Mass_wrt',
        'Radius_multiplier',
        'Radius_wrt',
        'Orbital_radius',
        'Orbital_period',
        'Eccentricity',
        'Detection_method'
    ],
    'Description': [
        'Name of the planet as per given by NASA.',
        'Distance of the planet from earth in light years.',
        'Brightness of the planet, the brighter the planet the lower number is assigned to the planet.',
        'Type of the planet, these types are derived from our solar system planets.',
        'Year in which planet got discovered.',
        'Mass multiplier of the planet with mass_wrt planet.',
        'Mass of the planet in comparison with the mass of planets of our solar system.',
        'Radius multiplier of the planet with radius_wrt planet.',
        'Radius of the planet in comparison with the radius of planets of our solar system.',
        'Orbital radius of planets orbiting around their sun (in AU).',
        'Time in years taken by those planets to complete 1 orbit of their star',
        'Eccentricity basically tells how circular is the orbitting path, eccentricity close to 0 means orbitting path is nearly circular',
        'Method used by NASA to find that exoplanet'
    ],
}
df_dicionario = pd.DataFrame(dictionary)
pd.set_option('display.max_colwidth', None)

display(df_dicionario)

,Column,Description
0,Name,Name of the planet as per given by NASA.
1,Distance,Distance of the planet from earth in light years.
2,Stellar_magnitude,"Brightness of the planet, the brighter the planet the lower number is assigned to the planet."
3,Planet_type,"Type of the planet, these types are derived from our solar system planets."
4,Discovery_year,Year in which planet got discovered.
5,Mass_multiplier,Mass multiplier of the planet with mass_wrt planet.
6,Mass_wrt,Mass of the planet in comparison with the mass of planets of our solar system.
7,Radius_multiplier,Radius multiplier of the planet with radius_wrt planet.
8,Radius_wrt,Radius of the planet in comparison with the radius of planets of our solar system.
9,Orbital_radius,Orbital radius of planets orbiting around their sun (in AU).
10,Orbital_period,Time in years taken by those planets to complete 1 orbit of their star
11,Eccentricity,"Eccentricity basically tells how circular is the orbitting path, eccentricity close to 0 means orbitting path is nearly circular"
12,Detection_method,Method used by NASA to find that exoplanet

In [16]:
display(df.describe())

,distance,stellar_magnitude,discovery_year,mass_multiplier,radius_multiplier,orbital_radius,orbital_period,eccentricity
count,5233.000000,5089.000000,5250.000000,5227.000000,5233.000000,4961.000000,5.250000e+03,5250.000000
mean,2167.168737,12.683738,2015.732190,6.434812,1.015121,6.962942,4.791509e+02,0.063568
std,3245.522087,3.107571,4.307336,12.972727,0.603479,138.673600,1.680445e+04,0.141424
min,4.000000,0.872000,1992.000000,0.020000,0.200000,0.004400,2.737851e-04,-0.520000
25%,389.000000,10.939000,2014.000000,1.804000,0.325000,0.053000,1.259411e-02,0.000000
50%,1371.000000,13.543000,2016.000000,4.170140,1.120000,0.102800,3.449692e-02,0.000000
75%,2779.000000,15.021000,2018.000000,8.000000,1.410000,0.286000,1.442163e-01,0.060000
max,27727.000000,44.610000,2023.000000,752.000000,6.900000,7506.000000,1.101370e+06,0.950000

In [30]:
df.head(5)

,name,distance,stellar_magnitude,planet_type,discovery_year,mass_multiplier,mass_wrt,radius_multiplier,radius_wrt,orbital_radius,orbital_period,eccentricity,detection_method
0,11 Comae Berenices b,304.0,4.72307,Gas Giant,2007,19.40000,Jupiter,1.08,Jupiter,1.290000,0.892539,0.23,Radial Velocity
1,11 Ursae Minoris b,409.0,5.01300,Gas Giant,2009,14.74000,Jupiter,1.09,Jupiter,1.530000,1.400000,0.08,Radial Velocity
2,14 Andromedae b,246.0,5.23133,Gas Giant,2008,4.80000,Jupiter,1.15,Jupiter,0.830000,0.508693,0.00,Radial Velocity
3,14 Herculis b,58.0,6.61935,Gas Giant,2002,8.13881,Jupiter,1.12,Jupiter,2.773069,4.800000,0.37,Radial Velocity
4,16 Cygni B b,69.0,6.21500,Gas Giant,1996,1.78000,Jupiter,1.20,Jupiter,1.660000,2.200000,0.68,Radial Velocity